<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoTaxHelper.Application\CryptoTaxHelper.Application.csproj" />
    <ProjectReference Include="..\CryptoTaxHelper.Infrastructure\CryptoTaxHelper.Infrastructure.csproj" />
  </ItemGroup>

</Project>
